version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./sql:/sql
